## Numpy Array basics
[[Source] w3resource NumPy exercises](https://www.w3resource.com/python-exercises/numpy/index-array.php)


In [0]:
import numpy as np

### #10
Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [2]:
# A[start:end:step]
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [3]:
y = np.arange(1,41).reshape(5,8)
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [4]:
y[1:4:2] # y[1]부터 y[4]전까지 step 2

array([[ 9, 10, 11, 12, 13, 14, 15, 16],
       [25, 26, 27, 28, 29, 30, 31, 32]])

In [5]:
y[::2] # y[0]부터 step 2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [6]:
y[:, ::2] # all rows, columns with step 2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [7]:
y[::2, :] # rows: step 2, column: all

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [8]:
y[::2, :2] # rows: step 2, column: before the index 2

array([[ 1,  2],
       [17, 18],
       [33, 34]])

In [9]:
y[::2, ::2] # rows: step 2, column: step 2

array([[ 1,  3,  5,  7],
       [17, 19, 21, 23],
       [33, 35, 37, 39]])

### #20
Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

Example

Array1: [0, 10, 20, 40, 60, 80], Array2: [10, 30, 40, 50, 70, 90]

Set difference between two arrays:
[0, 20, 60, 80]

In [10]:
a = np.array([0, 10, 20, 40, 60, 80])
b = np.array([10, 30, 40, 50, 70, 90])

np.setdiff1d(a, b)

array([ 0, 20, 60, 80])

In [11]:
np.intersect1d(a,b)

array([10, 40])

In [12]:
np.union1d(a, b)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### #30
Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).

first_names = (‘Betsey’, ‘Shelley’, ‘Lanell’, ‘Genesis’, ‘Margery’)

last_names = (‘Battle’, ‘Brien’, ‘Plotner’, ‘Stahl’, ‘Woolum’)


Expected Output:
[1 3 2 4 0]

In [13]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
x
# lexsort(first_names, last_names): sort by last_name first, then sort by first_name
# index is returned
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.lexsort.html 

array([1, 3, 2, 4, 0])

In [14]:
np.argsort(first_names) # arg가 붙으면 결과가 index

array([1, 4, 3, 0, 2])

In [15]:
np.sort(first_names)

array(['Betsey', 'Genesis', 'Lanell', 'Margery', 'Shelley'], dtype='<U7')

### #40

Write a NumPy program to create a new array of 3*5, filled with 2. 

Expected Output:
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]

In [16]:
a = np.ones((3,5), dtype='int')
a += a
a

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

### #50
Write a NumPy program to find the 4th element of a specified array. 


Example:

[ [ 2, 4, 6],
[ 6, 8, 10]]

4th element of the array: 6



In [17]:
np.array([[2,4,6], [6, 8, 10]], dtype='int').reshape(6,)[3]

6

### #60
Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array. 
 
Sample array: (10,20,30), (40,50,60)

Expected Output:
[[[10 40]]
[[20 50]]
[[30 60]]]

![Example](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-60.png)

In [18]:
a = np.array([[10], [20], [30]])
b = np.array([[40], [50], [60]])
c = np.dstack((a,b))
c

# dstack:
# 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 
# 가장 안쪽의 원소의 차원이 증가한다. 
# 즉 가장 내부의 숫자 원소가 배열이 된다. 
# shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.


array([[[10, 40]],

       [[20, 50]],

       [[30, 60]]])

In [19]:
c.shape

(3, 1, 2)

In [20]:
np.hstack((a,b))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [21]:
np.hstack((a,b)).shape

(3, 2)

In [22]:
np.vstack((a,b))

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

### #70
Write a NumPy program to create display every element of a NumPy array.

Expected Output:
0 1 2 3 4 5 6 7 8 9 10 11

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### #80
Write a NumPy program to convert a NumPy array into Python list structure. 

Expected Output:

Original array elements:
[[0 1]
[2 3]
[4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]

In [24]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
b = a.tolist()
b

[[0, 1], [2, 3], [4, 5]]

### #90
Write a NumPy program to remove the negative values in a NumPy array with 0. 


Expected Output:

Original array:
[-1 -4 0 2 3 4 5 -6]

Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]

In [26]:
a = np.array([-1, -4, 0, 3, 4, 1,-10])
np.where(a<0, 0, a)

array([0, 0, 0, 3, 4, 1, 0])

In [27]:
a = np.array([-1, -4, 0, 3, 4, 1,-10])
a[a<0] = 0
a

array([0, 0, 0, 3, 4, 1, 0])

### #100
 Write a NumPy program to take values from a source array and put them at specified indices of another array. 
 

Expected Output:
[ 10. 10. 20. 30. 30.]

Put 0 and 40 in first and fifth position of the above array

Array x after put two values: [ 0. 10. 20. 30. 40.]

In [28]:
a = np.array([10, 10, 20, 30, 30], dtype='float')
a[0] = 0
a[4] = 40
a

array([ 0., 10., 20., 30., 40.])

In [29]:
x = np.array([10, 10, 20, 30, 30], float)
y = np.array([0, 40, 60], float) 
x.put([0, 4], y)
x

array([ 0., 10., 20., 30., 40.])